services:
  db:
    image: postgres:15
    container_name: db-exchanger
    environment:
      POSTGRES_DB: gw-exchanger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./test_postgres_data:/var/lib/postgresql/data
