grpc:
  host: "localhost"
  port: 50051

logging:
  level: "debug"                # Уровень логирования: debug, info, warn, error
  format: "json"                # Формат логов: text, json
  output_file: ""               # Файл для записи логов (пусто для вывода в консоль)
  kafka_topic: ""
  kafka_broker: ""

database:
  dsn: postgres://postgres:postgres@localhost:5432/gw-exchanger?sslmode=disable

# Приоритет подгрузки переменных - .env!